const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT = 'LOGOUT';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

export { LOGIN_FAILURE, LOGIN_START, LOGIN_SUCCESS, LOGOUT };
